### ISSUE TITLE
Section 2.3 Remote sensing LLM-powered agent

### ISSUE THREAD

**Issue by Chen-Yang-Liu** [zytx121/Awesome-VLGFM#2]
**This work is very good!! I found a related work:**

- **Change-Agent: Toward Interactive Comprehensive Remote Sensing Change Interpretation and Analysis** [[paper]](https://ieeexplore.ieee.org/abstract/document/10591792) [[code]](https://github.com/Chen-Yang-Liu/Change-Agent)
  - (2024. 03) IEEE Transactions on Geoscience and Remote Sensing

**Comment by zytx121** [comment]
Thank you very much, we have updated this excellent work today.
